const Facturas = [{ id: '0',
                    Cliente: "Hakim",
                    Empresa: "Sobrero y Cagnolo",
                    Tipo: 'Factura',
                    Fecha:'20/07/22',
                    MontoPago: 0,
                    Estado:'Pendiente',
                    Numero: 12536,
                    Importe: 850000,
                  },
                  { id: '1',
                  Cliente: "Ricardo",
                  Empresa: "Sobrero y Cagnolo",
                  Tipo: 'Remito',
                  Fecha:'20/07/22',
                  MontoPago: 0,
                  Paga:true,
                  Estado:'Pendiente',
                  Numero: 12536,
                  Importe: 850000,
                },
                { id: '2',
                    Cliente: "Roberto",
                    Empresa: "Sobrero y Cagnolo",
                    Tipo: 'Factura',
                    Fecha:'14/08/2022',
                    MontoPago: 0,
                    Paga:true,
                    Estado:'Pendiente',
                    Numero: 12536,
                    Importe: 850000,
                  },
                  { id: '3',
                    Cliente: "Joaquin",
                    Empresa: "Sobrero y Cagnolo",
                    Tipo: 'Factura',
                    Fecha:'03/02/2022',
                    MontoPago: 0,
                    Paga:false,
                    Estado:'Pendiente',
                    Numero: 12536,
                    Importe: 850000,
                  },
                  { id: '4',
                    Cliente: "Raul",
                    Empresa: "Sobrero y Cagnolo",
                    Tipo: 'Remito',
                    Fecha:'02/02/2022',
                    MontoPago: 0,
                    Paga:false,
                    Estado:'Pendiente',
                    Numero: 12536,
                    Importe: 850000,
                  },
            ]
            


            const clientes =[
              { razonSocial:'Hakim',
                numclienteemp1:15,
                numclienteemp2:21,
                direccion:'hola 12',
                mail: 'soycliente@hotmail.com',
                telefono:2235658965,
              },
              { razonSocial:'Jorge',
                numclienteemp1:3,
                numclienteemp2:15,
                direccion:'colon 123',
                mail: 'soycliente@hotmail.com',
                telefono:2235658965,
              },
              { razonSocial:'Javier',
                numclienteemp1:35,
                numclienteemp2:26,
                direccion:'españa 12345',
                mail: 'soycliente@hotmail.com',
                telefono:2235658965,
              },
              { razonSocial:'Roberto',
                numclienteemp1:25,
                numclienteemp2:99,
                direccion:'Roberto',
                mail: 'soycliente@hotmail.com',
                telefono:2235658965,
              },
              { razonSocial:'Ricardo',
                numclienteemp1:35,
                numclienteemp2:14,
                direccion:'luro 2030',
                mail: 'soycliente@hotmail.com',
                telefono:2235658965,
              },
              { razonSocial:'Raul',
                numclienteemp1:15,
                numclienteemp2:21,
                direccion:'hola 12',
                mail: 'soycliente@hotmail.com',
                telefono:2235658965,
              },
              { razonSocial:'Joaquin',
                numclienteemp1:15,
                numclienteemp2:21,
                direccion:'hola 12',
                mail: 'soycliente@hotmail.com',
                telefono:2235658965,
              },


            ]


           export const GetCurrentAccount =()=> {
                return new Promise ((resolve) =>{
                    setTimeout(() =>{
                        resolve(Facturas)
                    },1000)


                })
            }
